Update patch set 10
Patch Set 10:

> Patch Set 10: Code-Review-1
> 
> Can't build with error:
> 
> # github.com/SamsungSLAV/weles/server/operations/artifacts
> server/operations/artifacts/artifact_lister_responses.go:62:13: undefined: weles.ArtifactInfoExt

I just  downloaded this PS and built it just fine.
ArtifactInfoExt is added in previous patch.

Anyway this patch will be abandoned due to pagination change in the API. Paginator object will have to be sent in the body rather than using query parameters. This change is for consistency with Boruta.

Patch-set: 10
Reviewer: Gerrit User 1015231 <1015231@d5d70762-12d0-45a1-890d-524b12d3f735>